
/* Copyright (c) 2022-2025 Douglas H. Summerville (dsummer@binghamton.edu) 
 *
 * Created from scraped data which is Copyright (c) 2022 Raspberry Pi
 * (Trading) Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef RP2040_IO_QSPI_H
#define RP2040_IO_QSPI_H

#include <stdint.h>

#define ALL1 ((uint32_t)0xFFFFFFFF)

typedef struct{
		uint32_t gpio_qspi_sclk_status;
		uint32_t gpio_qspi_sclk_ctrl;
		uint32_t gpio_qspi_ss_status;
		uint32_t gpio_qspi_ss_ctrl;
		uint32_t gpio_qspi_sd0_status;
		uint32_t gpio_qspi_sd0_ctrl;
		uint32_t gpio_qspi_sd1_status;
		uint32_t gpio_qspi_sd1_ctrl;
		uint32_t gpio_qspi_sd2_status;
		uint32_t gpio_qspi_sd2_ctrl;
		uint32_t gpio_qspi_sd3_status;
		uint32_t gpio_qspi_sd3_ctrl;
		uint32_t intr;
		uint32_t proc0_inte;
		uint32_t proc0_intf;
		uint32_t proc0_ints;
		uint32_t proc1_inte;
		uint32_t proc1_intf;
		uint32_t proc1_ints;
		uint32_t dormant_wake_inte;
		uint32_t dormant_wake_intf;
		uint32_t dormant_wake_ints;
		uint32_t RSVD0[1002];
		uint32_t xor_gpio_qspi_sclk_status;
		uint32_t xor_gpio_qspi_sclk_ctrl;
		uint32_t xor_gpio_qspi_ss_status;
		uint32_t xor_gpio_qspi_ss_ctrl;
		uint32_t xor_gpio_qspi_sd0_status;
		uint32_t xor_gpio_qspi_sd0_ctrl;
		uint32_t xor_gpio_qspi_sd1_status;
		uint32_t xor_gpio_qspi_sd1_ctrl;
		uint32_t xor_gpio_qspi_sd2_status;
		uint32_t xor_gpio_qspi_sd2_ctrl;
		uint32_t xor_gpio_qspi_sd3_status;
		uint32_t xor_gpio_qspi_sd3_ctrl;
		uint32_t xor_intr;
		uint32_t xor_proc0_inte;
		uint32_t xor_proc0_intf;
		uint32_t xor_proc0_ints;
		uint32_t xor_proc1_inte;
		uint32_t xor_proc1_intf;
		uint32_t xor_proc1_ints;
		uint32_t xor_dormant_wake_inte;
		uint32_t xor_dormant_wake_intf;
		uint32_t xor_dormant_wake_ints;
		uint32_t RSVDxor_0[1002];
		uint32_t set_gpio_qspi_sclk_status;
		uint32_t set_gpio_qspi_sclk_ctrl;
		uint32_t set_gpio_qspi_ss_status;
		uint32_t set_gpio_qspi_ss_ctrl;
		uint32_t set_gpio_qspi_sd0_status;
		uint32_t set_gpio_qspi_sd0_ctrl;
		uint32_t set_gpio_qspi_sd1_status;
		uint32_t set_gpio_qspi_sd1_ctrl;
		uint32_t set_gpio_qspi_sd2_status;
		uint32_t set_gpio_qspi_sd2_ctrl;
		uint32_t set_gpio_qspi_sd3_status;
		uint32_t set_gpio_qspi_sd3_ctrl;
		uint32_t set_intr;
		uint32_t set_proc0_inte;
		uint32_t set_proc0_intf;
		uint32_t set_proc0_ints;
		uint32_t set_proc1_inte;
		uint32_t set_proc1_intf;
		uint32_t set_proc1_ints;
		uint32_t set_dormant_wake_inte;
		uint32_t set_dormant_wake_intf;
		uint32_t set_dormant_wake_ints;
		uint32_t RSVDset_0[1002];
		uint32_t clr_gpio_qspi_sclk_status;
		uint32_t clr_gpio_qspi_sclk_ctrl;
		uint32_t clr_gpio_qspi_ss_status;
		uint32_t clr_gpio_qspi_ss_ctrl;
		uint32_t clr_gpio_qspi_sd0_status;
		uint32_t clr_gpio_qspi_sd0_ctrl;
		uint32_t clr_gpio_qspi_sd1_status;
		uint32_t clr_gpio_qspi_sd1_ctrl;
		uint32_t clr_gpio_qspi_sd2_status;
		uint32_t clr_gpio_qspi_sd2_ctrl;
		uint32_t clr_gpio_qspi_sd3_status;
		uint32_t clr_gpio_qspi_sd3_ctrl;
		uint32_t clr_intr;
		uint32_t clr_proc0_inte;
		uint32_t clr_proc0_intf;
		uint32_t clr_proc0_ints;
		uint32_t clr_proc1_inte;
		uint32_t clr_proc1_intf;
		uint32_t clr_proc1_ints;
		uint32_t clr_dormant_wake_inte;
		uint32_t clr_dormant_wake_intf;
		uint32_t clr_dormant_wake_ints;
		uint32_t RSVDclr_0[1002];
} IO_QSPI_REG_BLOCKS;

#define io_qspi ((IO_QSPI_REG_BLOCKS volatile *)0x40018000)

/*GPIO_QSPI_SCLK_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQFROMPAD(v) (((v)&0x1)<<24)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQFROMPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INTOPERI(v) (((v)&0x1)<<19)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INTOPERI_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_INTOPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OEFROMPERI(v) (((v)&0x1)<<12)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OEFROMPERI_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_OEFROMPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTFROMPERI(v) (((v)&0x1)<<8)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTFROMPERI_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTFROMPERI(ALL1)

/*GPIO_QSPI_SCLK_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER(v) (((v)&0x3)<<8)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SS_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQFROMPAD(v) (((v)&0x1)<<24)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQFROMPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_IRQFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INTOPERI(v) (((v)&0x1)<<19)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INTOPERI_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_INTOPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OEFROMPERI(v) (((v)&0x1)<<12)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OEFROMPERI_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_OEFROMPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTFROMPERI(v) (((v)&0x1)<<8)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTFROMPERI_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_OUTFROMPERI(ALL1)

/*GPIO_QSPI_SS_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER(v) (((v)&0x3)<<8)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD0_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQFROMPAD(v) (((v)&0x1)<<24)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INTOPERI(v) (((v)&0x1)<<19)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INTOPERI_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_INTOPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OEFROMPERI(v) (((v)&0x1)<<12)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OEFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_OEFROMPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTFROMPERI(v) (((v)&0x1)<<8)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTFROMPERI(ALL1)

/*GPIO_QSPI_SD0_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER(v) (((v)&0x3)<<8)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD1_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQFROMPAD(v) (((v)&0x1)<<24)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INTOPERI(v) (((v)&0x1)<<19)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INTOPERI_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_INTOPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OEFROMPERI(v) (((v)&0x1)<<12)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OEFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_OEFROMPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTFROMPERI(v) (((v)&0x1)<<8)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTFROMPERI(ALL1)

/*GPIO_QSPI_SD1_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER(v) (((v)&0x3)<<8)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD2_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQFROMPAD(v) (((v)&0x1)<<24)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INTOPERI(v) (((v)&0x1)<<19)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INTOPERI_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_INTOPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OEFROMPERI(v) (((v)&0x1)<<12)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OEFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_OEFROMPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTFROMPERI(v) (((v)&0x1)<<8)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTFROMPERI(ALL1)

/*GPIO_QSPI_SD2_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER(v) (((v)&0x3)<<8)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD3_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQFROMPAD(v) (((v)&0x1)<<24)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INTOPERI(v) (((v)&0x1)<<19)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INTOPERI_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_INTOPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OEFROMPERI(v) (((v)&0x1)<<12)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OEFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_OEFROMPERI(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTFROMPERI(v) (((v)&0x1)<<8)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTFROMPERI_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTFROMPERI(ALL1)

/*GPIO_QSPI_SD3_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER(v) (((v)&0x3)<<8)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL(ALL1)

/*INTR Register macros*/

#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*PROC0_INTE Register macros*/

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*PROC0_INTF Register macros*/

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*PROC0_INTS Register macros*/

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*PROC1_INTE Register macros*/

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*PROC1_INTF Register macros*/

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*PROC1_INTS Register macros*/

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*DORMANT_WAKE_INTE Register macros*/

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*DORMANT_WAKE_INTF Register macros*/

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

/*DORMANT_WAKE_INTS Register macros*/

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)

#endif