
/* Copyright (c) 2022-2025 Douglas H. Summerville (dsummer@binghamton.edu) 
 *
 * Created from scraped data which is Copyright (c) 2022 Raspberry Pi
 * (Trading) Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef RP2040_USB_H
#define RP2040_USB_H

#include <stdint.h>

#define ALL1 ((uint32_t)0xFFFFFFFF)

typedef struct{
		uint32_t addr_endp;
		uint32_t addr_endp1;
		uint32_t addr_endp2;
		uint32_t addr_endp3;
		uint32_t addr_endp4;
		uint32_t addr_endp5;
		uint32_t addr_endp6;
		uint32_t addr_endp7;
		uint32_t addr_endp8;
		uint32_t addr_endp9;
		uint32_t addr_endp10;
		uint32_t addr_endp11;
		uint32_t addr_endp12;
		uint32_t addr_endp13;
		uint32_t addr_endp14;
		uint32_t addr_endp15;
		uint32_t main_ctrl;
		uint32_t sof_wr;
		uint32_t sof_rd;
		uint32_t sie_ctrl;
		uint32_t sie_status;
		uint32_t int_ep_ctrl;
		uint32_t buff_status;
		uint32_t buff_cpu_should_handle;
		uint32_t ep_abort;
		uint32_t ep_abort_done;
		uint32_t ep_stall_arm;
		uint32_t nak_poll;
		uint32_t ep_status_stall_nak;
		uint32_t usb_muxing;
		uint32_t usb_pwr;
		uint32_t usbphy_direct;
		uint32_t usbphy_direct_override;
		uint32_t usbphy_trim;
		uint32_t RSVD0;
		uint32_t intr;
		uint32_t inte;
		uint32_t intf;
		uint32_t ints;
		uint32_t RSVD1[985];
		uint32_t xor_addr_endp;
		uint32_t xor_addr_endp1;
		uint32_t xor_addr_endp2;
		uint32_t xor_addr_endp3;
		uint32_t xor_addr_endp4;
		uint32_t xor_addr_endp5;
		uint32_t xor_addr_endp6;
		uint32_t xor_addr_endp7;
		uint32_t xor_addr_endp8;
		uint32_t xor_addr_endp9;
		uint32_t xor_addr_endp10;
		uint32_t xor_addr_endp11;
		uint32_t xor_addr_endp12;
		uint32_t xor_addr_endp13;
		uint32_t xor_addr_endp14;
		uint32_t xor_addr_endp15;
		uint32_t xor_main_ctrl;
		uint32_t xor_sof_wr;
		uint32_t xor_sof_rd;
		uint32_t xor_sie_ctrl;
		uint32_t xor_sie_status;
		uint32_t xor_int_ep_ctrl;
		uint32_t xor_buff_status;
		uint32_t xor_buff_cpu_should_handle;
		uint32_t xor_ep_abort;
		uint32_t xor_ep_abort_done;
		uint32_t xor_ep_stall_arm;
		uint32_t xor_nak_poll;
		uint32_t xor_ep_status_stall_nak;
		uint32_t xor_usb_muxing;
		uint32_t xor_usb_pwr;
		uint32_t xor_usbphy_direct;
		uint32_t xor_usbphy_direct_override;
		uint32_t xor_usbphy_trim;
		uint32_t RSVDxor_0;
		uint32_t xor_intr;
		uint32_t xor_inte;
		uint32_t xor_intf;
		uint32_t xor_ints;
		uint32_t RSVDxor_1[985];
		uint32_t set_addr_endp;
		uint32_t set_addr_endp1;
		uint32_t set_addr_endp2;
		uint32_t set_addr_endp3;
		uint32_t set_addr_endp4;
		uint32_t set_addr_endp5;
		uint32_t set_addr_endp6;
		uint32_t set_addr_endp7;
		uint32_t set_addr_endp8;
		uint32_t set_addr_endp9;
		uint32_t set_addr_endp10;
		uint32_t set_addr_endp11;
		uint32_t set_addr_endp12;
		uint32_t set_addr_endp13;
		uint32_t set_addr_endp14;
		uint32_t set_addr_endp15;
		uint32_t set_main_ctrl;
		uint32_t set_sof_wr;
		uint32_t set_sof_rd;
		uint32_t set_sie_ctrl;
		uint32_t set_sie_status;
		uint32_t set_int_ep_ctrl;
		uint32_t set_buff_status;
		uint32_t set_buff_cpu_should_handle;
		uint32_t set_ep_abort;
		uint32_t set_ep_abort_done;
		uint32_t set_ep_stall_arm;
		uint32_t set_nak_poll;
		uint32_t set_ep_status_stall_nak;
		uint32_t set_usb_muxing;
		uint32_t set_usb_pwr;
		uint32_t set_usbphy_direct;
		uint32_t set_usbphy_direct_override;
		uint32_t set_usbphy_trim;
		uint32_t RSVDset_0;
		uint32_t set_intr;
		uint32_t set_inte;
		uint32_t set_intf;
		uint32_t set_ints;
		uint32_t RSVDset_1[985];
		uint32_t clr_addr_endp;
		uint32_t clr_addr_endp1;
		uint32_t clr_addr_endp2;
		uint32_t clr_addr_endp3;
		uint32_t clr_addr_endp4;
		uint32_t clr_addr_endp5;
		uint32_t clr_addr_endp6;
		uint32_t clr_addr_endp7;
		uint32_t clr_addr_endp8;
		uint32_t clr_addr_endp9;
		uint32_t clr_addr_endp10;
		uint32_t clr_addr_endp11;
		uint32_t clr_addr_endp12;
		uint32_t clr_addr_endp13;
		uint32_t clr_addr_endp14;
		uint32_t clr_addr_endp15;
		uint32_t clr_main_ctrl;
		uint32_t clr_sof_wr;
		uint32_t clr_sof_rd;
		uint32_t clr_sie_ctrl;
		uint32_t clr_sie_status;
		uint32_t clr_int_ep_ctrl;
		uint32_t clr_buff_status;
		uint32_t clr_buff_cpu_should_handle;
		uint32_t clr_ep_abort;
		uint32_t clr_ep_abort_done;
		uint32_t clr_ep_stall_arm;
		uint32_t clr_nak_poll;
		uint32_t clr_ep_status_stall_nak;
		uint32_t clr_usb_muxing;
		uint32_t clr_usb_pwr;
		uint32_t clr_usbphy_direct;
		uint32_t clr_usbphy_direct_override;
		uint32_t clr_usbphy_trim;
		uint32_t RSVDclr_0;
		uint32_t clr_intr;
		uint32_t clr_inte;
		uint32_t clr_intf;
		uint32_t clr_ints;
		uint32_t RSVDclr_1[985];
} USBCTRL_REG_BLOCKS;

#define usbctrl ((USBCTRL_REG_BLOCKS volatile *)0x50110000)

/*ADDR_ENDP Register macros*/

#define USBCTRL_ADDR_ENDP_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP_ENDPOINT_MASK USBCTRL_ADDR_ENDP_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP_ADDRESS_MASK USBCTRL_ADDR_ENDP_ADDRESS(ALL1)

/*ADDR_ENDP1 Register macros*/

#define USBCTRL_ADDR_ENDP1_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP1_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP1_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP1_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP1_INTEP_DIR_MASK USBCTRL_ADDR_ENDP1_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP1_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP1_ENDPOINT_MASK USBCTRL_ADDR_ENDP1_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP1_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP1_ADDRESS_MASK USBCTRL_ADDR_ENDP1_ADDRESS(ALL1)

/*ADDR_ENDP2 Register macros*/

#define USBCTRL_ADDR_ENDP2_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP2_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP2_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP2_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP2_INTEP_DIR_MASK USBCTRL_ADDR_ENDP2_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP2_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP2_ENDPOINT_MASK USBCTRL_ADDR_ENDP2_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP2_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP2_ADDRESS_MASK USBCTRL_ADDR_ENDP2_ADDRESS(ALL1)

/*ADDR_ENDP3 Register macros*/

#define USBCTRL_ADDR_ENDP3_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP3_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP3_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP3_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP3_INTEP_DIR_MASK USBCTRL_ADDR_ENDP3_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP3_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP3_ENDPOINT_MASK USBCTRL_ADDR_ENDP3_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP3_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP3_ADDRESS_MASK USBCTRL_ADDR_ENDP3_ADDRESS(ALL1)

/*ADDR_ENDP4 Register macros*/

#define USBCTRL_ADDR_ENDP4_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP4_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP4_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP4_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP4_INTEP_DIR_MASK USBCTRL_ADDR_ENDP4_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP4_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP4_ENDPOINT_MASK USBCTRL_ADDR_ENDP4_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP4_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP4_ADDRESS_MASK USBCTRL_ADDR_ENDP4_ADDRESS(ALL1)

/*ADDR_ENDP5 Register macros*/

#define USBCTRL_ADDR_ENDP5_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP5_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP5_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP5_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP5_INTEP_DIR_MASK USBCTRL_ADDR_ENDP5_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP5_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP5_ENDPOINT_MASK USBCTRL_ADDR_ENDP5_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP5_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP5_ADDRESS_MASK USBCTRL_ADDR_ENDP5_ADDRESS(ALL1)

/*ADDR_ENDP6 Register macros*/

#define USBCTRL_ADDR_ENDP6_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP6_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP6_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP6_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP6_INTEP_DIR_MASK USBCTRL_ADDR_ENDP6_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP6_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP6_ENDPOINT_MASK USBCTRL_ADDR_ENDP6_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP6_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP6_ADDRESS_MASK USBCTRL_ADDR_ENDP6_ADDRESS(ALL1)

/*ADDR_ENDP7 Register macros*/

#define USBCTRL_ADDR_ENDP7_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP7_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP7_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP7_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP7_INTEP_DIR_MASK USBCTRL_ADDR_ENDP7_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP7_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP7_ENDPOINT_MASK USBCTRL_ADDR_ENDP7_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP7_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP7_ADDRESS_MASK USBCTRL_ADDR_ENDP7_ADDRESS(ALL1)

/*ADDR_ENDP8 Register macros*/

#define USBCTRL_ADDR_ENDP8_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP8_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP8_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP8_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP8_INTEP_DIR_MASK USBCTRL_ADDR_ENDP8_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP8_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP8_ENDPOINT_MASK USBCTRL_ADDR_ENDP8_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP8_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP8_ADDRESS_MASK USBCTRL_ADDR_ENDP8_ADDRESS(ALL1)

/*ADDR_ENDP9 Register macros*/

#define USBCTRL_ADDR_ENDP9_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP9_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP9_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP9_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP9_INTEP_DIR_MASK USBCTRL_ADDR_ENDP9_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP9_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP9_ENDPOINT_MASK USBCTRL_ADDR_ENDP9_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP9_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP9_ADDRESS_MASK USBCTRL_ADDR_ENDP9_ADDRESS(ALL1)

/*ADDR_ENDP10 Register macros*/

#define USBCTRL_ADDR_ENDP10_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP10_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP10_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP10_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP10_INTEP_DIR_MASK USBCTRL_ADDR_ENDP10_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP10_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP10_ENDPOINT_MASK USBCTRL_ADDR_ENDP10_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP10_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP10_ADDRESS_MASK USBCTRL_ADDR_ENDP10_ADDRESS(ALL1)

/*ADDR_ENDP11 Register macros*/

#define USBCTRL_ADDR_ENDP11_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP11_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP11_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP11_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP11_INTEP_DIR_MASK USBCTRL_ADDR_ENDP11_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP11_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP11_ENDPOINT_MASK USBCTRL_ADDR_ENDP11_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP11_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP11_ADDRESS_MASK USBCTRL_ADDR_ENDP11_ADDRESS(ALL1)

/*ADDR_ENDP12 Register macros*/

#define USBCTRL_ADDR_ENDP12_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP12_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP12_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP12_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP12_INTEP_DIR_MASK USBCTRL_ADDR_ENDP12_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP12_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP12_ENDPOINT_MASK USBCTRL_ADDR_ENDP12_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP12_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP12_ADDRESS_MASK USBCTRL_ADDR_ENDP12_ADDRESS(ALL1)

/*ADDR_ENDP13 Register macros*/

#define USBCTRL_ADDR_ENDP13_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP13_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP13_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP13_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP13_INTEP_DIR_MASK USBCTRL_ADDR_ENDP13_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP13_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP13_ENDPOINT_MASK USBCTRL_ADDR_ENDP13_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP13_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP13_ADDRESS_MASK USBCTRL_ADDR_ENDP13_ADDRESS(ALL1)

/*ADDR_ENDP14 Register macros*/

#define USBCTRL_ADDR_ENDP14_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP14_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP14_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP14_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP14_INTEP_DIR_MASK USBCTRL_ADDR_ENDP14_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP14_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP14_ENDPOINT_MASK USBCTRL_ADDR_ENDP14_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP14_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP14_ADDRESS_MASK USBCTRL_ADDR_ENDP14_ADDRESS(ALL1)

/*ADDR_ENDP15 Register macros*/

#define USBCTRL_ADDR_ENDP15_INTEP_PREAMBLE(v) (((v)&0x1)<<26)
#define USBCTRL_ADDR_ENDP15_INTEP_PREAMBLE_MASK USBCTRL_ADDR_ENDP15_INTEP_PREAMBLE(ALL1)
#define USBCTRL_ADDR_ENDP15_INTEP_DIR(v) (((v)&0x1)<<25)
#define USBCTRL_ADDR_ENDP15_INTEP_DIR_MASK USBCTRL_ADDR_ENDP15_INTEP_DIR(ALL1)
#define USBCTRL_ADDR_ENDP15_ENDPOINT(v) (((v)&0xf)<<16)
#define USBCTRL_ADDR_ENDP15_ENDPOINT_MASK USBCTRL_ADDR_ENDP15_ENDPOINT(ALL1)
#define USBCTRL_ADDR_ENDP15_ADDRESS(v) (((v)&0x7f)<<0)
#define USBCTRL_ADDR_ENDP15_ADDRESS_MASK USBCTRL_ADDR_ENDP15_ADDRESS(ALL1)

/*MAIN_CTRL Register macros*/

#define USBCTRL_MAIN_CTRL_SIM_TIMING(v) (((v)&0x1)<<31)
#define USBCTRL_MAIN_CTRL_SIM_TIMING_MASK USBCTRL_MAIN_CTRL_SIM_TIMING(ALL1)
#define USBCTRL_MAIN_CTRL_HOST_NDEVICE(v) (((v)&0x1)<<1)
#define USBCTRL_MAIN_CTRL_HOST_NDEVICE_MASK USBCTRL_MAIN_CTRL_HOST_NDEVICE(ALL1)
#define USBCTRL_MAIN_CTRL_CONTROLLER_EN(v) (((v)&0x1)<<0)
#define USBCTRL_MAIN_CTRL_CONTROLLER_EN_MASK USBCTRL_MAIN_CTRL_CONTROLLER_EN(ALL1)

/*SOF_WR Register macros*/

#define USBCTRL_SOF_WR_COUNT(v) (((v)&0x7ff)<<0)
#define USBCTRL_SOF_WR_COUNT_MASK USBCTRL_SOF_WR_COUNT(ALL1)

/*SOF_RD Register macros*/

#define USBCTRL_SOF_RD_COUNT(v) (((v)&0x7ff)<<0)
#define USBCTRL_SOF_RD_COUNT_MASK USBCTRL_SOF_RD_COUNT(ALL1)

/*SIE_CTRL Register macros*/

#define USBCTRL_SIE_CTRL_EP0_INT_STALL(v) (((v)&0x1)<<31)
#define USBCTRL_SIE_CTRL_EP0_INT_STALL_MASK USBCTRL_SIE_CTRL_EP0_INT_STALL(ALL1)
#define USBCTRL_SIE_CTRL_EP0_DOUBLE_BUF(v) (((v)&0x1)<<30)
#define USBCTRL_SIE_CTRL_EP0_DOUBLE_BUF_MASK USBCTRL_SIE_CTRL_EP0_DOUBLE_BUF(ALL1)
#define USBCTRL_SIE_CTRL_EP0_INT_1BUF(v) (((v)&0x1)<<29)
#define USBCTRL_SIE_CTRL_EP0_INT_1BUF_MASK USBCTRL_SIE_CTRL_EP0_INT_1BUF(ALL1)
#define USBCTRL_SIE_CTRL_EP0_INT_2BUF(v) (((v)&0x1)<<28)
#define USBCTRL_SIE_CTRL_EP0_INT_2BUF_MASK USBCTRL_SIE_CTRL_EP0_INT_2BUF(ALL1)
#define USBCTRL_SIE_CTRL_EP0_INT_NAK(v) (((v)&0x1)<<27)
#define USBCTRL_SIE_CTRL_EP0_INT_NAK_MASK USBCTRL_SIE_CTRL_EP0_INT_NAK(ALL1)
#define USBCTRL_SIE_CTRL_DIRECT_EN(v) (((v)&0x1)<<26)
#define USBCTRL_SIE_CTRL_DIRECT_EN_MASK USBCTRL_SIE_CTRL_DIRECT_EN(ALL1)
#define USBCTRL_SIE_CTRL_DIRECT_DP(v) (((v)&0x1)<<25)
#define USBCTRL_SIE_CTRL_DIRECT_DP_MASK USBCTRL_SIE_CTRL_DIRECT_DP(ALL1)
#define USBCTRL_SIE_CTRL_DIRECT_DM(v) (((v)&0x1)<<24)
#define USBCTRL_SIE_CTRL_DIRECT_DM_MASK USBCTRL_SIE_CTRL_DIRECT_DM(ALL1)
#define USBCTRL_SIE_CTRL_TRANSCEIVER_PD(v) (((v)&0x1)<<18)
#define USBCTRL_SIE_CTRL_TRANSCEIVER_PD_MASK USBCTRL_SIE_CTRL_TRANSCEIVER_PD(ALL1)
#define USBCTRL_SIE_CTRL_RPU_OPT(v) (((v)&0x1)<<17)
#define USBCTRL_SIE_CTRL_RPU_OPT_MASK USBCTRL_SIE_CTRL_RPU_OPT(ALL1)
#define USBCTRL_SIE_CTRL_PULLUP_EN(v) (((v)&0x1)<<16)
#define USBCTRL_SIE_CTRL_PULLUP_EN_MASK USBCTRL_SIE_CTRL_PULLUP_EN(ALL1)
#define USBCTRL_SIE_CTRL_PULLDOWN_EN(v) (((v)&0x1)<<15)
#define USBCTRL_SIE_CTRL_PULLDOWN_EN_MASK USBCTRL_SIE_CTRL_PULLDOWN_EN(ALL1)
#define USBCTRL_SIE_CTRL_RESET_BUS(v) (((v)&0x1)<<13)
#define USBCTRL_SIE_CTRL_RESET_BUS_MASK USBCTRL_SIE_CTRL_RESET_BUS(ALL1)
#define USBCTRL_SIE_CTRL_RESUME(v) (((v)&0x1)<<12)
#define USBCTRL_SIE_CTRL_RESUME_MASK USBCTRL_SIE_CTRL_RESUME(ALL1)
#define USBCTRL_SIE_CTRL_VBUS_EN(v) (((v)&0x1)<<11)
#define USBCTRL_SIE_CTRL_VBUS_EN_MASK USBCTRL_SIE_CTRL_VBUS_EN(ALL1)
#define USBCTRL_SIE_CTRL_KEEP_ALIVE_EN(v) (((v)&0x1)<<10)
#define USBCTRL_SIE_CTRL_KEEP_ALIVE_EN_MASK USBCTRL_SIE_CTRL_KEEP_ALIVE_EN(ALL1)
#define USBCTRL_SIE_CTRL_SOF_EN(v) (((v)&0x1)<<9)
#define USBCTRL_SIE_CTRL_SOF_EN_MASK USBCTRL_SIE_CTRL_SOF_EN(ALL1)
#define USBCTRL_SIE_CTRL_SOF_SYNC(v) (((v)&0x1)<<8)
#define USBCTRL_SIE_CTRL_SOF_SYNC_MASK USBCTRL_SIE_CTRL_SOF_SYNC(ALL1)
#define USBCTRL_SIE_CTRL_PREAMBLE_EN(v) (((v)&0x1)<<6)
#define USBCTRL_SIE_CTRL_PREAMBLE_EN_MASK USBCTRL_SIE_CTRL_PREAMBLE_EN(ALL1)
#define USBCTRL_SIE_CTRL_STOP_TRANS(v) (((v)&0x1)<<4)
#define USBCTRL_SIE_CTRL_STOP_TRANS_MASK USBCTRL_SIE_CTRL_STOP_TRANS(ALL1)
#define USBCTRL_SIE_CTRL_RECEIVE_DATA(v) (((v)&0x1)<<3)
#define USBCTRL_SIE_CTRL_RECEIVE_DATA_MASK USBCTRL_SIE_CTRL_RECEIVE_DATA(ALL1)
#define USBCTRL_SIE_CTRL_SEND_DATA(v) (((v)&0x1)<<2)
#define USBCTRL_SIE_CTRL_SEND_DATA_MASK USBCTRL_SIE_CTRL_SEND_DATA(ALL1)
#define USBCTRL_SIE_CTRL_SEND_SETUP(v) (((v)&0x1)<<1)
#define USBCTRL_SIE_CTRL_SEND_SETUP_MASK USBCTRL_SIE_CTRL_SEND_SETUP(ALL1)
#define USBCTRL_SIE_CTRL_START_TRANS(v) (((v)&0x1)<<0)
#define USBCTRL_SIE_CTRL_START_TRANS_MASK USBCTRL_SIE_CTRL_START_TRANS(ALL1)

/*SIE_STATUS Register macros*/

#define USBCTRL_SIE_STATUS_DATA_SEQ_ERROR(v) (((v)&0x1)<<31)
#define USBCTRL_SIE_STATUS_DATA_SEQ_ERROR_MASK USBCTRL_SIE_STATUS_DATA_SEQ_ERROR(ALL1)
#define USBCTRL_SIE_STATUS_ACK_REC(v) (((v)&0x1)<<30)
#define USBCTRL_SIE_STATUS_ACK_REC_MASK USBCTRL_SIE_STATUS_ACK_REC(ALL1)
#define USBCTRL_SIE_STATUS_STALL_REC(v) (((v)&0x1)<<29)
#define USBCTRL_SIE_STATUS_STALL_REC_MASK USBCTRL_SIE_STATUS_STALL_REC(ALL1)
#define USBCTRL_SIE_STATUS_NAK_REC(v) (((v)&0x1)<<28)
#define USBCTRL_SIE_STATUS_NAK_REC_MASK USBCTRL_SIE_STATUS_NAK_REC(ALL1)
#define USBCTRL_SIE_STATUS_RX_TIMEOUT(v) (((v)&0x1)<<27)
#define USBCTRL_SIE_STATUS_RX_TIMEOUT_MASK USBCTRL_SIE_STATUS_RX_TIMEOUT(ALL1)
#define USBCTRL_SIE_STATUS_RX_OVERFLOW(v) (((v)&0x1)<<26)
#define USBCTRL_SIE_STATUS_RX_OVERFLOW_MASK USBCTRL_SIE_STATUS_RX_OVERFLOW(ALL1)
#define USBCTRL_SIE_STATUS_BIT_STUFF_ERROR(v) (((v)&0x1)<<25)
#define USBCTRL_SIE_STATUS_BIT_STUFF_ERROR_MASK USBCTRL_SIE_STATUS_BIT_STUFF_ERROR(ALL1)
#define USBCTRL_SIE_STATUS_CRC_ERROR(v) (((v)&0x1)<<24)
#define USBCTRL_SIE_STATUS_CRC_ERROR_MASK USBCTRL_SIE_STATUS_CRC_ERROR(ALL1)
#define USBCTRL_SIE_STATUS_BUS_RESET(v) (((v)&0x1)<<19)
#define USBCTRL_SIE_STATUS_BUS_RESET_MASK USBCTRL_SIE_STATUS_BUS_RESET(ALL1)
#define USBCTRL_SIE_STATUS_TRANS_COMPLETE(v) (((v)&0x1)<<18)
#define USBCTRL_SIE_STATUS_TRANS_COMPLETE_MASK USBCTRL_SIE_STATUS_TRANS_COMPLETE(ALL1)
#define USBCTRL_SIE_STATUS_SETUP_REC(v) (((v)&0x1)<<17)
#define USBCTRL_SIE_STATUS_SETUP_REC_MASK USBCTRL_SIE_STATUS_SETUP_REC(ALL1)
#define USBCTRL_SIE_STATUS_CONNECTED(v) (((v)&0x1)<<16)
#define USBCTRL_SIE_STATUS_CONNECTED_MASK USBCTRL_SIE_STATUS_CONNECTED(ALL1)
#define USBCTRL_SIE_STATUS_RESUME(v) (((v)&0x1)<<11)
#define USBCTRL_SIE_STATUS_RESUME_MASK USBCTRL_SIE_STATUS_RESUME(ALL1)
#define USBCTRL_SIE_STATUS_VBUS_OVER_CURR(v) (((v)&0x1)<<10)
#define USBCTRL_SIE_STATUS_VBUS_OVER_CURR_MASK USBCTRL_SIE_STATUS_VBUS_OVER_CURR(ALL1)
#define USBCTRL_SIE_STATUS_SPEED(v) (((v)&0x3)<<8)
#define USBCTRL_SIE_STATUS_SPEED_MASK USBCTRL_SIE_STATUS_SPEED(ALL1)
#define USBCTRL_SIE_STATUS_SUSPENDED(v) (((v)&0x1)<<4)
#define USBCTRL_SIE_STATUS_SUSPENDED_MASK USBCTRL_SIE_STATUS_SUSPENDED(ALL1)
#define USBCTRL_SIE_STATUS_LINE_STATE(v) (((v)&0x3)<<2)
#define USBCTRL_SIE_STATUS_LINE_STATE_MASK USBCTRL_SIE_STATUS_LINE_STATE(ALL1)
#define USBCTRL_SIE_STATUS_VBUS_DETECTED(v) (((v)&0x1)<<0)
#define USBCTRL_SIE_STATUS_VBUS_DETECTED_MASK USBCTRL_SIE_STATUS_VBUS_DETECTED(ALL1)

/*INT_EP_CTRL Register macros*/

#define USBCTRL_INT_EP_CTRL_INT_EP_ACTIVE(v) (((v)&0x7fff)<<1)
#define USBCTRL_INT_EP_CTRL_INT_EP_ACTIVE_MASK USBCTRL_INT_EP_CTRL_INT_EP_ACTIVE(ALL1)

/*BUFF_STATUS Register macros*/

#define USBCTRL_BUFF_STATUS_EP15_OUT(v) (((v)&0x1)<<31)
#define USBCTRL_BUFF_STATUS_EP15_OUT_MASK USBCTRL_BUFF_STATUS_EP15_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP15_IN(v) (((v)&0x1)<<30)
#define USBCTRL_BUFF_STATUS_EP15_IN_MASK USBCTRL_BUFF_STATUS_EP15_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP14_OUT(v) (((v)&0x1)<<29)
#define USBCTRL_BUFF_STATUS_EP14_OUT_MASK USBCTRL_BUFF_STATUS_EP14_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP14_IN(v) (((v)&0x1)<<28)
#define USBCTRL_BUFF_STATUS_EP14_IN_MASK USBCTRL_BUFF_STATUS_EP14_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP13_OUT(v) (((v)&0x1)<<27)
#define USBCTRL_BUFF_STATUS_EP13_OUT_MASK USBCTRL_BUFF_STATUS_EP13_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP13_IN(v) (((v)&0x1)<<26)
#define USBCTRL_BUFF_STATUS_EP13_IN_MASK USBCTRL_BUFF_STATUS_EP13_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP12_OUT(v) (((v)&0x1)<<25)
#define USBCTRL_BUFF_STATUS_EP12_OUT_MASK USBCTRL_BUFF_STATUS_EP12_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP12_IN(v) (((v)&0x1)<<24)
#define USBCTRL_BUFF_STATUS_EP12_IN_MASK USBCTRL_BUFF_STATUS_EP12_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP11_OUT(v) (((v)&0x1)<<23)
#define USBCTRL_BUFF_STATUS_EP11_OUT_MASK USBCTRL_BUFF_STATUS_EP11_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP11_IN(v) (((v)&0x1)<<22)
#define USBCTRL_BUFF_STATUS_EP11_IN_MASK USBCTRL_BUFF_STATUS_EP11_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP10_OUT(v) (((v)&0x1)<<21)
#define USBCTRL_BUFF_STATUS_EP10_OUT_MASK USBCTRL_BUFF_STATUS_EP10_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP10_IN(v) (((v)&0x1)<<20)
#define USBCTRL_BUFF_STATUS_EP10_IN_MASK USBCTRL_BUFF_STATUS_EP10_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP9_OUT(v) (((v)&0x1)<<19)
#define USBCTRL_BUFF_STATUS_EP9_OUT_MASK USBCTRL_BUFF_STATUS_EP9_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP9_IN(v) (((v)&0x1)<<18)
#define USBCTRL_BUFF_STATUS_EP9_IN_MASK USBCTRL_BUFF_STATUS_EP9_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP8_OUT(v) (((v)&0x1)<<17)
#define USBCTRL_BUFF_STATUS_EP8_OUT_MASK USBCTRL_BUFF_STATUS_EP8_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP8_IN(v) (((v)&0x1)<<16)
#define USBCTRL_BUFF_STATUS_EP8_IN_MASK USBCTRL_BUFF_STATUS_EP8_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP7_OUT(v) (((v)&0x1)<<15)
#define USBCTRL_BUFF_STATUS_EP7_OUT_MASK USBCTRL_BUFF_STATUS_EP7_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP7_IN(v) (((v)&0x1)<<14)
#define USBCTRL_BUFF_STATUS_EP7_IN_MASK USBCTRL_BUFF_STATUS_EP7_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP6_OUT(v) (((v)&0x1)<<13)
#define USBCTRL_BUFF_STATUS_EP6_OUT_MASK USBCTRL_BUFF_STATUS_EP6_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP6_IN(v) (((v)&0x1)<<12)
#define USBCTRL_BUFF_STATUS_EP6_IN_MASK USBCTRL_BUFF_STATUS_EP6_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP5_OUT(v) (((v)&0x1)<<11)
#define USBCTRL_BUFF_STATUS_EP5_OUT_MASK USBCTRL_BUFF_STATUS_EP5_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP5_IN(v) (((v)&0x1)<<10)
#define USBCTRL_BUFF_STATUS_EP5_IN_MASK USBCTRL_BUFF_STATUS_EP5_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP4_OUT(v) (((v)&0x1)<<9)
#define USBCTRL_BUFF_STATUS_EP4_OUT_MASK USBCTRL_BUFF_STATUS_EP4_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP4_IN(v) (((v)&0x1)<<8)
#define USBCTRL_BUFF_STATUS_EP4_IN_MASK USBCTRL_BUFF_STATUS_EP4_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP3_OUT(v) (((v)&0x1)<<7)
#define USBCTRL_BUFF_STATUS_EP3_OUT_MASK USBCTRL_BUFF_STATUS_EP3_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP3_IN(v) (((v)&0x1)<<6)
#define USBCTRL_BUFF_STATUS_EP3_IN_MASK USBCTRL_BUFF_STATUS_EP3_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP2_OUT(v) (((v)&0x1)<<5)
#define USBCTRL_BUFF_STATUS_EP2_OUT_MASK USBCTRL_BUFF_STATUS_EP2_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP2_IN(v) (((v)&0x1)<<4)
#define USBCTRL_BUFF_STATUS_EP2_IN_MASK USBCTRL_BUFF_STATUS_EP2_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP1_OUT(v) (((v)&0x1)<<3)
#define USBCTRL_BUFF_STATUS_EP1_OUT_MASK USBCTRL_BUFF_STATUS_EP1_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP1_IN(v) (((v)&0x1)<<2)
#define USBCTRL_BUFF_STATUS_EP1_IN_MASK USBCTRL_BUFF_STATUS_EP1_IN(ALL1)
#define USBCTRL_BUFF_STATUS_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_BUFF_STATUS_EP0_OUT_MASK USBCTRL_BUFF_STATUS_EP0_OUT(ALL1)
#define USBCTRL_BUFF_STATUS_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_BUFF_STATUS_EP0_IN_MASK USBCTRL_BUFF_STATUS_EP0_IN(ALL1)

/*BUFF_CPU_SHOULD_HANDLE Register macros*/

#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP15_OUT(v) (((v)&0x1)<<31)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP15_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP15_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP15_IN(v) (((v)&0x1)<<30)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP15_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP15_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP14_OUT(v) (((v)&0x1)<<29)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP14_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP14_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP14_IN(v) (((v)&0x1)<<28)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP14_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP14_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP13_OUT(v) (((v)&0x1)<<27)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP13_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP13_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP13_IN(v) (((v)&0x1)<<26)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP13_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP13_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP12_OUT(v) (((v)&0x1)<<25)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP12_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP12_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP12_IN(v) (((v)&0x1)<<24)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP12_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP12_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP11_OUT(v) (((v)&0x1)<<23)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP11_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP11_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP11_IN(v) (((v)&0x1)<<22)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP11_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP11_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP10_OUT(v) (((v)&0x1)<<21)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP10_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP10_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP10_IN(v) (((v)&0x1)<<20)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP10_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP10_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP9_OUT(v) (((v)&0x1)<<19)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP9_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP9_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP9_IN(v) (((v)&0x1)<<18)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP9_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP9_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP8_OUT(v) (((v)&0x1)<<17)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP8_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP8_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP8_IN(v) (((v)&0x1)<<16)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP8_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP8_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP7_OUT(v) (((v)&0x1)<<15)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP7_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP7_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP7_IN(v) (((v)&0x1)<<14)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP7_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP7_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP6_OUT(v) (((v)&0x1)<<13)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP6_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP6_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP6_IN(v) (((v)&0x1)<<12)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP6_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP6_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP5_OUT(v) (((v)&0x1)<<11)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP5_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP5_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP5_IN(v) (((v)&0x1)<<10)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP5_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP5_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP4_OUT(v) (((v)&0x1)<<9)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP4_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP4_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP4_IN(v) (((v)&0x1)<<8)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP4_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP4_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP3_OUT(v) (((v)&0x1)<<7)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP3_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP3_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP3_IN(v) (((v)&0x1)<<6)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP3_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP3_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP2_OUT(v) (((v)&0x1)<<5)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP2_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP2_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP2_IN(v) (((v)&0x1)<<4)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP2_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP2_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP1_OUT(v) (((v)&0x1)<<3)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP1_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP1_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP1_IN(v) (((v)&0x1)<<2)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP1_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP1_IN(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP0_OUT_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP0_OUT(ALL1)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP0_IN_MASK USBCTRL_BUFF_CPU_SHOULD_HANDLE_EP0_IN(ALL1)

/*EP_ABORT Register macros*/

#define USBCTRL_EP_ABORT_EP15_OUT(v) (((v)&0x1)<<31)
#define USBCTRL_EP_ABORT_EP15_OUT_MASK USBCTRL_EP_ABORT_EP15_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP15_IN(v) (((v)&0x1)<<30)
#define USBCTRL_EP_ABORT_EP15_IN_MASK USBCTRL_EP_ABORT_EP15_IN(ALL1)
#define USBCTRL_EP_ABORT_EP14_OUT(v) (((v)&0x1)<<29)
#define USBCTRL_EP_ABORT_EP14_OUT_MASK USBCTRL_EP_ABORT_EP14_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP14_IN(v) (((v)&0x1)<<28)
#define USBCTRL_EP_ABORT_EP14_IN_MASK USBCTRL_EP_ABORT_EP14_IN(ALL1)
#define USBCTRL_EP_ABORT_EP13_OUT(v) (((v)&0x1)<<27)
#define USBCTRL_EP_ABORT_EP13_OUT_MASK USBCTRL_EP_ABORT_EP13_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP13_IN(v) (((v)&0x1)<<26)
#define USBCTRL_EP_ABORT_EP13_IN_MASK USBCTRL_EP_ABORT_EP13_IN(ALL1)
#define USBCTRL_EP_ABORT_EP12_OUT(v) (((v)&0x1)<<25)
#define USBCTRL_EP_ABORT_EP12_OUT_MASK USBCTRL_EP_ABORT_EP12_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP12_IN(v) (((v)&0x1)<<24)
#define USBCTRL_EP_ABORT_EP12_IN_MASK USBCTRL_EP_ABORT_EP12_IN(ALL1)
#define USBCTRL_EP_ABORT_EP11_OUT(v) (((v)&0x1)<<23)
#define USBCTRL_EP_ABORT_EP11_OUT_MASK USBCTRL_EP_ABORT_EP11_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP11_IN(v) (((v)&0x1)<<22)
#define USBCTRL_EP_ABORT_EP11_IN_MASK USBCTRL_EP_ABORT_EP11_IN(ALL1)
#define USBCTRL_EP_ABORT_EP10_OUT(v) (((v)&0x1)<<21)
#define USBCTRL_EP_ABORT_EP10_OUT_MASK USBCTRL_EP_ABORT_EP10_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP10_IN(v) (((v)&0x1)<<20)
#define USBCTRL_EP_ABORT_EP10_IN_MASK USBCTRL_EP_ABORT_EP10_IN(ALL1)
#define USBCTRL_EP_ABORT_EP9_OUT(v) (((v)&0x1)<<19)
#define USBCTRL_EP_ABORT_EP9_OUT_MASK USBCTRL_EP_ABORT_EP9_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP9_IN(v) (((v)&0x1)<<18)
#define USBCTRL_EP_ABORT_EP9_IN_MASK USBCTRL_EP_ABORT_EP9_IN(ALL1)
#define USBCTRL_EP_ABORT_EP8_OUT(v) (((v)&0x1)<<17)
#define USBCTRL_EP_ABORT_EP8_OUT_MASK USBCTRL_EP_ABORT_EP8_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP8_IN(v) (((v)&0x1)<<16)
#define USBCTRL_EP_ABORT_EP8_IN_MASK USBCTRL_EP_ABORT_EP8_IN(ALL1)
#define USBCTRL_EP_ABORT_EP7_OUT(v) (((v)&0x1)<<15)
#define USBCTRL_EP_ABORT_EP7_OUT_MASK USBCTRL_EP_ABORT_EP7_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP7_IN(v) (((v)&0x1)<<14)
#define USBCTRL_EP_ABORT_EP7_IN_MASK USBCTRL_EP_ABORT_EP7_IN(ALL1)
#define USBCTRL_EP_ABORT_EP6_OUT(v) (((v)&0x1)<<13)
#define USBCTRL_EP_ABORT_EP6_OUT_MASK USBCTRL_EP_ABORT_EP6_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP6_IN(v) (((v)&0x1)<<12)
#define USBCTRL_EP_ABORT_EP6_IN_MASK USBCTRL_EP_ABORT_EP6_IN(ALL1)
#define USBCTRL_EP_ABORT_EP5_OUT(v) (((v)&0x1)<<11)
#define USBCTRL_EP_ABORT_EP5_OUT_MASK USBCTRL_EP_ABORT_EP5_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP5_IN(v) (((v)&0x1)<<10)
#define USBCTRL_EP_ABORT_EP5_IN_MASK USBCTRL_EP_ABORT_EP5_IN(ALL1)
#define USBCTRL_EP_ABORT_EP4_OUT(v) (((v)&0x1)<<9)
#define USBCTRL_EP_ABORT_EP4_OUT_MASK USBCTRL_EP_ABORT_EP4_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP4_IN(v) (((v)&0x1)<<8)
#define USBCTRL_EP_ABORT_EP4_IN_MASK USBCTRL_EP_ABORT_EP4_IN(ALL1)
#define USBCTRL_EP_ABORT_EP3_OUT(v) (((v)&0x1)<<7)
#define USBCTRL_EP_ABORT_EP3_OUT_MASK USBCTRL_EP_ABORT_EP3_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP3_IN(v) (((v)&0x1)<<6)
#define USBCTRL_EP_ABORT_EP3_IN_MASK USBCTRL_EP_ABORT_EP3_IN(ALL1)
#define USBCTRL_EP_ABORT_EP2_OUT(v) (((v)&0x1)<<5)
#define USBCTRL_EP_ABORT_EP2_OUT_MASK USBCTRL_EP_ABORT_EP2_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP2_IN(v) (((v)&0x1)<<4)
#define USBCTRL_EP_ABORT_EP2_IN_MASK USBCTRL_EP_ABORT_EP2_IN(ALL1)
#define USBCTRL_EP_ABORT_EP1_OUT(v) (((v)&0x1)<<3)
#define USBCTRL_EP_ABORT_EP1_OUT_MASK USBCTRL_EP_ABORT_EP1_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP1_IN(v) (((v)&0x1)<<2)
#define USBCTRL_EP_ABORT_EP1_IN_MASK USBCTRL_EP_ABORT_EP1_IN(ALL1)
#define USBCTRL_EP_ABORT_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_EP_ABORT_EP0_OUT_MASK USBCTRL_EP_ABORT_EP0_OUT(ALL1)
#define USBCTRL_EP_ABORT_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_EP_ABORT_EP0_IN_MASK USBCTRL_EP_ABORT_EP0_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP15_OUT(v) (((v)&0x1)<<31)
#define USBCTRL_EP_ABORT_DONE_EP15_OUT_MASK USBCTRL_EP_ABORT_DONE_EP15_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP15_IN(v) (((v)&0x1)<<30)
#define USBCTRL_EP_ABORT_DONE_EP15_IN_MASK USBCTRL_EP_ABORT_DONE_EP15_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP14_OUT(v) (((v)&0x1)<<29)
#define USBCTRL_EP_ABORT_DONE_EP14_OUT_MASK USBCTRL_EP_ABORT_DONE_EP14_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP14_IN(v) (((v)&0x1)<<28)
#define USBCTRL_EP_ABORT_DONE_EP14_IN_MASK USBCTRL_EP_ABORT_DONE_EP14_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP13_OUT(v) (((v)&0x1)<<27)
#define USBCTRL_EP_ABORT_DONE_EP13_OUT_MASK USBCTRL_EP_ABORT_DONE_EP13_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP13_IN(v) (((v)&0x1)<<26)
#define USBCTRL_EP_ABORT_DONE_EP13_IN_MASK USBCTRL_EP_ABORT_DONE_EP13_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP12_OUT(v) (((v)&0x1)<<25)
#define USBCTRL_EP_ABORT_DONE_EP12_OUT_MASK USBCTRL_EP_ABORT_DONE_EP12_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP12_IN(v) (((v)&0x1)<<24)
#define USBCTRL_EP_ABORT_DONE_EP12_IN_MASK USBCTRL_EP_ABORT_DONE_EP12_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP11_OUT(v) (((v)&0x1)<<23)
#define USBCTRL_EP_ABORT_DONE_EP11_OUT_MASK USBCTRL_EP_ABORT_DONE_EP11_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP11_IN(v) (((v)&0x1)<<22)
#define USBCTRL_EP_ABORT_DONE_EP11_IN_MASK USBCTRL_EP_ABORT_DONE_EP11_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP10_OUT(v) (((v)&0x1)<<21)
#define USBCTRL_EP_ABORT_DONE_EP10_OUT_MASK USBCTRL_EP_ABORT_DONE_EP10_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP10_IN(v) (((v)&0x1)<<20)
#define USBCTRL_EP_ABORT_DONE_EP10_IN_MASK USBCTRL_EP_ABORT_DONE_EP10_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP9_OUT(v) (((v)&0x1)<<19)
#define USBCTRL_EP_ABORT_DONE_EP9_OUT_MASK USBCTRL_EP_ABORT_DONE_EP9_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP9_IN(v) (((v)&0x1)<<18)
#define USBCTRL_EP_ABORT_DONE_EP9_IN_MASK USBCTRL_EP_ABORT_DONE_EP9_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP8_OUT(v) (((v)&0x1)<<17)
#define USBCTRL_EP_ABORT_DONE_EP8_OUT_MASK USBCTRL_EP_ABORT_DONE_EP8_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP8_IN(v) (((v)&0x1)<<16)
#define USBCTRL_EP_ABORT_DONE_EP8_IN_MASK USBCTRL_EP_ABORT_DONE_EP8_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP7_OUT(v) (((v)&0x1)<<15)
#define USBCTRL_EP_ABORT_DONE_EP7_OUT_MASK USBCTRL_EP_ABORT_DONE_EP7_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP7_IN(v) (((v)&0x1)<<14)
#define USBCTRL_EP_ABORT_DONE_EP7_IN_MASK USBCTRL_EP_ABORT_DONE_EP7_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP6_OUT(v) (((v)&0x1)<<13)
#define USBCTRL_EP_ABORT_DONE_EP6_OUT_MASK USBCTRL_EP_ABORT_DONE_EP6_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP6_IN(v) (((v)&0x1)<<12)
#define USBCTRL_EP_ABORT_DONE_EP6_IN_MASK USBCTRL_EP_ABORT_DONE_EP6_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP5_OUT(v) (((v)&0x1)<<11)
#define USBCTRL_EP_ABORT_DONE_EP5_OUT_MASK USBCTRL_EP_ABORT_DONE_EP5_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP5_IN(v) (((v)&0x1)<<10)
#define USBCTRL_EP_ABORT_DONE_EP5_IN_MASK USBCTRL_EP_ABORT_DONE_EP5_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP4_OUT(v) (((v)&0x1)<<9)
#define USBCTRL_EP_ABORT_DONE_EP4_OUT_MASK USBCTRL_EP_ABORT_DONE_EP4_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP4_IN(v) (((v)&0x1)<<8)
#define USBCTRL_EP_ABORT_DONE_EP4_IN_MASK USBCTRL_EP_ABORT_DONE_EP4_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP3_OUT(v) (((v)&0x1)<<7)
#define USBCTRL_EP_ABORT_DONE_EP3_OUT_MASK USBCTRL_EP_ABORT_DONE_EP3_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP3_IN(v) (((v)&0x1)<<6)
#define USBCTRL_EP_ABORT_DONE_EP3_IN_MASK USBCTRL_EP_ABORT_DONE_EP3_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP2_OUT(v) (((v)&0x1)<<5)
#define USBCTRL_EP_ABORT_DONE_EP2_OUT_MASK USBCTRL_EP_ABORT_DONE_EP2_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP2_IN(v) (((v)&0x1)<<4)
#define USBCTRL_EP_ABORT_DONE_EP2_IN_MASK USBCTRL_EP_ABORT_DONE_EP2_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP1_OUT(v) (((v)&0x1)<<3)
#define USBCTRL_EP_ABORT_DONE_EP1_OUT_MASK USBCTRL_EP_ABORT_DONE_EP1_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP1_IN(v) (((v)&0x1)<<2)
#define USBCTRL_EP_ABORT_DONE_EP1_IN_MASK USBCTRL_EP_ABORT_DONE_EP1_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_EP_ABORT_DONE_EP0_OUT_MASK USBCTRL_EP_ABORT_DONE_EP0_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_EP_ABORT_DONE_EP0_IN_MASK USBCTRL_EP_ABORT_DONE_EP0_IN(ALL1)

/*EP_ABORT_DONE Register macros*/

#define USBCTRL_EP_ABORT_DONE_EP15_OUT(v) (((v)&0x1)<<31)
#define USBCTRL_EP_ABORT_DONE_EP15_OUT_MASK USBCTRL_EP_ABORT_DONE_EP15_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP15_IN(v) (((v)&0x1)<<30)
#define USBCTRL_EP_ABORT_DONE_EP15_IN_MASK USBCTRL_EP_ABORT_DONE_EP15_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP14_OUT(v) (((v)&0x1)<<29)
#define USBCTRL_EP_ABORT_DONE_EP14_OUT_MASK USBCTRL_EP_ABORT_DONE_EP14_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP14_IN(v) (((v)&0x1)<<28)
#define USBCTRL_EP_ABORT_DONE_EP14_IN_MASK USBCTRL_EP_ABORT_DONE_EP14_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP13_OUT(v) (((v)&0x1)<<27)
#define USBCTRL_EP_ABORT_DONE_EP13_OUT_MASK USBCTRL_EP_ABORT_DONE_EP13_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP13_IN(v) (((v)&0x1)<<26)
#define USBCTRL_EP_ABORT_DONE_EP13_IN_MASK USBCTRL_EP_ABORT_DONE_EP13_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP12_OUT(v) (((v)&0x1)<<25)
#define USBCTRL_EP_ABORT_DONE_EP12_OUT_MASK USBCTRL_EP_ABORT_DONE_EP12_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP12_IN(v) (((v)&0x1)<<24)
#define USBCTRL_EP_ABORT_DONE_EP12_IN_MASK USBCTRL_EP_ABORT_DONE_EP12_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP11_OUT(v) (((v)&0x1)<<23)
#define USBCTRL_EP_ABORT_DONE_EP11_OUT_MASK USBCTRL_EP_ABORT_DONE_EP11_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP11_IN(v) (((v)&0x1)<<22)
#define USBCTRL_EP_ABORT_DONE_EP11_IN_MASK USBCTRL_EP_ABORT_DONE_EP11_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP10_OUT(v) (((v)&0x1)<<21)
#define USBCTRL_EP_ABORT_DONE_EP10_OUT_MASK USBCTRL_EP_ABORT_DONE_EP10_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP10_IN(v) (((v)&0x1)<<20)
#define USBCTRL_EP_ABORT_DONE_EP10_IN_MASK USBCTRL_EP_ABORT_DONE_EP10_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP9_OUT(v) (((v)&0x1)<<19)
#define USBCTRL_EP_ABORT_DONE_EP9_OUT_MASK USBCTRL_EP_ABORT_DONE_EP9_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP9_IN(v) (((v)&0x1)<<18)
#define USBCTRL_EP_ABORT_DONE_EP9_IN_MASK USBCTRL_EP_ABORT_DONE_EP9_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP8_OUT(v) (((v)&0x1)<<17)
#define USBCTRL_EP_ABORT_DONE_EP8_OUT_MASK USBCTRL_EP_ABORT_DONE_EP8_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP8_IN(v) (((v)&0x1)<<16)
#define USBCTRL_EP_ABORT_DONE_EP8_IN_MASK USBCTRL_EP_ABORT_DONE_EP8_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP7_OUT(v) (((v)&0x1)<<15)
#define USBCTRL_EP_ABORT_DONE_EP7_OUT_MASK USBCTRL_EP_ABORT_DONE_EP7_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP7_IN(v) (((v)&0x1)<<14)
#define USBCTRL_EP_ABORT_DONE_EP7_IN_MASK USBCTRL_EP_ABORT_DONE_EP7_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP6_OUT(v) (((v)&0x1)<<13)
#define USBCTRL_EP_ABORT_DONE_EP6_OUT_MASK USBCTRL_EP_ABORT_DONE_EP6_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP6_IN(v) (((v)&0x1)<<12)
#define USBCTRL_EP_ABORT_DONE_EP6_IN_MASK USBCTRL_EP_ABORT_DONE_EP6_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP5_OUT(v) (((v)&0x1)<<11)
#define USBCTRL_EP_ABORT_DONE_EP5_OUT_MASK USBCTRL_EP_ABORT_DONE_EP5_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP5_IN(v) (((v)&0x1)<<10)
#define USBCTRL_EP_ABORT_DONE_EP5_IN_MASK USBCTRL_EP_ABORT_DONE_EP5_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP4_OUT(v) (((v)&0x1)<<9)
#define USBCTRL_EP_ABORT_DONE_EP4_OUT_MASK USBCTRL_EP_ABORT_DONE_EP4_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP4_IN(v) (((v)&0x1)<<8)
#define USBCTRL_EP_ABORT_DONE_EP4_IN_MASK USBCTRL_EP_ABORT_DONE_EP4_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP3_OUT(v) (((v)&0x1)<<7)
#define USBCTRL_EP_ABORT_DONE_EP3_OUT_MASK USBCTRL_EP_ABORT_DONE_EP3_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP3_IN(v) (((v)&0x1)<<6)
#define USBCTRL_EP_ABORT_DONE_EP3_IN_MASK USBCTRL_EP_ABORT_DONE_EP3_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP2_OUT(v) (((v)&0x1)<<5)
#define USBCTRL_EP_ABORT_DONE_EP2_OUT_MASK USBCTRL_EP_ABORT_DONE_EP2_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP2_IN(v) (((v)&0x1)<<4)
#define USBCTRL_EP_ABORT_DONE_EP2_IN_MASK USBCTRL_EP_ABORT_DONE_EP2_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP1_OUT(v) (((v)&0x1)<<3)
#define USBCTRL_EP_ABORT_DONE_EP1_OUT_MASK USBCTRL_EP_ABORT_DONE_EP1_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP1_IN(v) (((v)&0x1)<<2)
#define USBCTRL_EP_ABORT_DONE_EP1_IN_MASK USBCTRL_EP_ABORT_DONE_EP1_IN(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_EP_ABORT_DONE_EP0_OUT_MASK USBCTRL_EP_ABORT_DONE_EP0_OUT(ALL1)
#define USBCTRL_EP_ABORT_DONE_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_EP_ABORT_DONE_EP0_IN_MASK USBCTRL_EP_ABORT_DONE_EP0_IN(ALL1)

/*EP_STALL_ARM Register macros*/

#define USBCTRL_EP_STALL_ARM_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_EP_STALL_ARM_EP0_OUT_MASK USBCTRL_EP_STALL_ARM_EP0_OUT(ALL1)
#define USBCTRL_EP_STALL_ARM_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_EP_STALL_ARM_EP0_IN_MASK USBCTRL_EP_STALL_ARM_EP0_IN(ALL1)

/*NAK_POLL Register macros*/

#define USBCTRL_NAK_POLL_DELAY_FS(v) (((v)&0x3ff)<<16)
#define USBCTRL_NAK_POLL_DELAY_FS_MASK USBCTRL_NAK_POLL_DELAY_FS(ALL1)
#define USBCTRL_NAK_POLL_DELAY_LS(v) (((v)&0x3ff)<<0)
#define USBCTRL_NAK_POLL_DELAY_LS_MASK USBCTRL_NAK_POLL_DELAY_LS(ALL1)

/*EP_STATUS_STALL_NAK Register macros*/

#define USBCTRL_EP_STATUS_STALL_NAK_EP15_OUT(v) (((v)&0x1)<<31)
#define USBCTRL_EP_STATUS_STALL_NAK_EP15_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP15_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP15_IN(v) (((v)&0x1)<<30)
#define USBCTRL_EP_STATUS_STALL_NAK_EP15_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP15_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP14_OUT(v) (((v)&0x1)<<29)
#define USBCTRL_EP_STATUS_STALL_NAK_EP14_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP14_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP14_IN(v) (((v)&0x1)<<28)
#define USBCTRL_EP_STATUS_STALL_NAK_EP14_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP14_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP13_OUT(v) (((v)&0x1)<<27)
#define USBCTRL_EP_STATUS_STALL_NAK_EP13_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP13_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP13_IN(v) (((v)&0x1)<<26)
#define USBCTRL_EP_STATUS_STALL_NAK_EP13_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP13_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP12_OUT(v) (((v)&0x1)<<25)
#define USBCTRL_EP_STATUS_STALL_NAK_EP12_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP12_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP12_IN(v) (((v)&0x1)<<24)
#define USBCTRL_EP_STATUS_STALL_NAK_EP12_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP12_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP11_OUT(v) (((v)&0x1)<<23)
#define USBCTRL_EP_STATUS_STALL_NAK_EP11_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP11_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP11_IN(v) (((v)&0x1)<<22)
#define USBCTRL_EP_STATUS_STALL_NAK_EP11_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP11_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP10_OUT(v) (((v)&0x1)<<21)
#define USBCTRL_EP_STATUS_STALL_NAK_EP10_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP10_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP10_IN(v) (((v)&0x1)<<20)
#define USBCTRL_EP_STATUS_STALL_NAK_EP10_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP10_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP9_OUT(v) (((v)&0x1)<<19)
#define USBCTRL_EP_STATUS_STALL_NAK_EP9_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP9_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP9_IN(v) (((v)&0x1)<<18)
#define USBCTRL_EP_STATUS_STALL_NAK_EP9_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP9_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP8_OUT(v) (((v)&0x1)<<17)
#define USBCTRL_EP_STATUS_STALL_NAK_EP8_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP8_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP8_IN(v) (((v)&0x1)<<16)
#define USBCTRL_EP_STATUS_STALL_NAK_EP8_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP8_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP7_OUT(v) (((v)&0x1)<<15)
#define USBCTRL_EP_STATUS_STALL_NAK_EP7_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP7_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP7_IN(v) (((v)&0x1)<<14)
#define USBCTRL_EP_STATUS_STALL_NAK_EP7_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP7_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP6_OUT(v) (((v)&0x1)<<13)
#define USBCTRL_EP_STATUS_STALL_NAK_EP6_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP6_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP6_IN(v) (((v)&0x1)<<12)
#define USBCTRL_EP_STATUS_STALL_NAK_EP6_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP6_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP5_OUT(v) (((v)&0x1)<<11)
#define USBCTRL_EP_STATUS_STALL_NAK_EP5_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP5_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP5_IN(v) (((v)&0x1)<<10)
#define USBCTRL_EP_STATUS_STALL_NAK_EP5_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP5_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP4_OUT(v) (((v)&0x1)<<9)
#define USBCTRL_EP_STATUS_STALL_NAK_EP4_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP4_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP4_IN(v) (((v)&0x1)<<8)
#define USBCTRL_EP_STATUS_STALL_NAK_EP4_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP4_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP3_OUT(v) (((v)&0x1)<<7)
#define USBCTRL_EP_STATUS_STALL_NAK_EP3_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP3_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP3_IN(v) (((v)&0x1)<<6)
#define USBCTRL_EP_STATUS_STALL_NAK_EP3_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP3_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP2_OUT(v) (((v)&0x1)<<5)
#define USBCTRL_EP_STATUS_STALL_NAK_EP2_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP2_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP2_IN(v) (((v)&0x1)<<4)
#define USBCTRL_EP_STATUS_STALL_NAK_EP2_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP2_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP1_OUT(v) (((v)&0x1)<<3)
#define USBCTRL_EP_STATUS_STALL_NAK_EP1_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP1_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP1_IN(v) (((v)&0x1)<<2)
#define USBCTRL_EP_STATUS_STALL_NAK_EP1_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP1_IN(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP0_OUT(v) (((v)&0x1)<<1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP0_OUT_MASK USBCTRL_EP_STATUS_STALL_NAK_EP0_OUT(ALL1)
#define USBCTRL_EP_STATUS_STALL_NAK_EP0_IN(v) (((v)&0x1)<<0)
#define USBCTRL_EP_STATUS_STALL_NAK_EP0_IN_MASK USBCTRL_EP_STATUS_STALL_NAK_EP0_IN(ALL1)

/*USB_MUXING Register macros*/

#define USBCTRL_USB_MUXING_SOFTCON(v) (((v)&0x1)<<3)
#define USBCTRL_USB_MUXING_SOFTCON_MASK USBCTRL_USB_MUXING_SOFTCON(ALL1)
#define USBCTRL_USB_MUXING_TO_DIGITAL_PAD(v) (((v)&0x1)<<2)
#define USBCTRL_USB_MUXING_TO_DIGITAL_PAD_MASK USBCTRL_USB_MUXING_TO_DIGITAL_PAD(ALL1)
#define USBCTRL_USB_MUXING_TO_EXTPHY(v) (((v)&0x1)<<1)
#define USBCTRL_USB_MUXING_TO_EXTPHY_MASK USBCTRL_USB_MUXING_TO_EXTPHY(ALL1)
#define USBCTRL_USB_MUXING_TO_PHY(v) (((v)&0x1)<<0)
#define USBCTRL_USB_MUXING_TO_PHY_MASK USBCTRL_USB_MUXING_TO_PHY(ALL1)

/*USB_PWR Register macros*/

#define USBCTRL_USB_PWR_OVERCURR_DETECT_EN(v) (((v)&0x1)<<5)
#define USBCTRL_USB_PWR_OVERCURR_DETECT_EN_MASK USBCTRL_USB_PWR_OVERCURR_DETECT_EN(ALL1)
#define USBCTRL_USB_PWR_OVERCURR_DETECT(v) (((v)&0x1)<<4)
#define USBCTRL_USB_PWR_OVERCURR_DETECT_MASK USBCTRL_USB_PWR_OVERCURR_DETECT(ALL1)
#define USBCTRL_USB_PWR_VBUS_DETECT_OVERRIDE_EN(v) (((v)&0x1)<<3)
#define USBCTRL_USB_PWR_VBUS_DETECT_OVERRIDE_EN_MASK USBCTRL_USB_PWR_VBUS_DETECT_OVERRIDE_EN(ALL1)
#define USBCTRL_USB_PWR_VBUS_DETECT(v) (((v)&0x1)<<2)
#define USBCTRL_USB_PWR_VBUS_DETECT_MASK USBCTRL_USB_PWR_VBUS_DETECT(ALL1)
#define USBCTRL_USB_PWR_VBUS_EN_OVERRIDE_EN(v) (((v)&0x1)<<1)
#define USBCTRL_USB_PWR_VBUS_EN_OVERRIDE_EN_MASK USBCTRL_USB_PWR_VBUS_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USB_PWR_VBUS_EN(v) (((v)&0x1)<<0)
#define USBCTRL_USB_PWR_VBUS_EN_MASK USBCTRL_USB_PWR_VBUS_EN(ALL1)

/*USBPHY_DIRECT Register macros*/

#define USBCTRL_USBPHY_DIRECT_DM_OVV(v) (((v)&0x1)<<22)
#define USBCTRL_USBPHY_DIRECT_DM_OVV_MASK USBCTRL_USBPHY_DIRECT_DM_OVV(ALL1)
#define USBCTRL_USBPHY_DIRECT_DP_OVV(v) (((v)&0x1)<<21)
#define USBCTRL_USBPHY_DIRECT_DP_OVV_MASK USBCTRL_USBPHY_DIRECT_DP_OVV(ALL1)
#define USBCTRL_USBPHY_DIRECT_DM_OVCN(v) (((v)&0x1)<<20)
#define USBCTRL_USBPHY_DIRECT_DM_OVCN_MASK USBCTRL_USBPHY_DIRECT_DM_OVCN(ALL1)
#define USBCTRL_USBPHY_DIRECT_DP_OVCN(v) (((v)&0x1)<<19)
#define USBCTRL_USBPHY_DIRECT_DP_OVCN_MASK USBCTRL_USBPHY_DIRECT_DP_OVCN(ALL1)
#define USBCTRL_USBPHY_DIRECT_RX_DM(v) (((v)&0x1)<<18)
#define USBCTRL_USBPHY_DIRECT_RX_DM_MASK USBCTRL_USBPHY_DIRECT_RX_DM(ALL1)
#define USBCTRL_USBPHY_DIRECT_RX_DP(v) (((v)&0x1)<<17)
#define USBCTRL_USBPHY_DIRECT_RX_DP_MASK USBCTRL_USBPHY_DIRECT_RX_DP(ALL1)
#define USBCTRL_USBPHY_DIRECT_RX_DD(v) (((v)&0x1)<<16)
#define USBCTRL_USBPHY_DIRECT_RX_DD_MASK USBCTRL_USBPHY_DIRECT_RX_DD(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_DIFFMODE(v) (((v)&0x1)<<15)
#define USBCTRL_USBPHY_DIRECT_TX_DIFFMODE_MASK USBCTRL_USBPHY_DIRECT_TX_DIFFMODE(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_FSSLEW(v) (((v)&0x1)<<14)
#define USBCTRL_USBPHY_DIRECT_TX_FSSLEW_MASK USBCTRL_USBPHY_DIRECT_TX_FSSLEW(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_PD(v) (((v)&0x1)<<13)
#define USBCTRL_USBPHY_DIRECT_TX_PD_MASK USBCTRL_USBPHY_DIRECT_TX_PD(ALL1)
#define USBCTRL_USBPHY_DIRECT_RX_PD(v) (((v)&0x1)<<12)
#define USBCTRL_USBPHY_DIRECT_RX_PD_MASK USBCTRL_USBPHY_DIRECT_RX_PD(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_DM(v) (((v)&0x1)<<11)
#define USBCTRL_USBPHY_DIRECT_TX_DM_MASK USBCTRL_USBPHY_DIRECT_TX_DM(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_DP(v) (((v)&0x1)<<10)
#define USBCTRL_USBPHY_DIRECT_TX_DP_MASK USBCTRL_USBPHY_DIRECT_TX_DP(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_DM_OE(v) (((v)&0x1)<<9)
#define USBCTRL_USBPHY_DIRECT_TX_DM_OE_MASK USBCTRL_USBPHY_DIRECT_TX_DM_OE(ALL1)
#define USBCTRL_USBPHY_DIRECT_TX_DP_OE(v) (((v)&0x1)<<8)
#define USBCTRL_USBPHY_DIRECT_TX_DP_OE_MASK USBCTRL_USBPHY_DIRECT_TX_DP_OE(ALL1)
#define USBCTRL_USBPHY_DIRECT_DM_PULLDN_EN(v) (((v)&0x1)<<6)
#define USBCTRL_USBPHY_DIRECT_DM_PULLDN_EN_MASK USBCTRL_USBPHY_DIRECT_DM_PULLDN_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_DM_PULLUP_EN(v) (((v)&0x1)<<5)
#define USBCTRL_USBPHY_DIRECT_DM_PULLUP_EN_MASK USBCTRL_USBPHY_DIRECT_DM_PULLUP_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_DM_PULLUP_HISEL(v) (((v)&0x1)<<4)
#define USBCTRL_USBPHY_DIRECT_DM_PULLUP_HISEL_MASK USBCTRL_USBPHY_DIRECT_DM_PULLUP_HISEL(ALL1)
#define USBCTRL_USBPHY_DIRECT_DP_PULLDN_EN(v) (((v)&0x1)<<2)
#define USBCTRL_USBPHY_DIRECT_DP_PULLDN_EN_MASK USBCTRL_USBPHY_DIRECT_DP_PULLDN_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_DP_PULLUP_EN(v) (((v)&0x1)<<1)
#define USBCTRL_USBPHY_DIRECT_DP_PULLUP_EN_MASK USBCTRL_USBPHY_DIRECT_DP_PULLUP_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_DP_PULLUP_HISEL(v) (((v)&0x1)<<0)
#define USBCTRL_USBPHY_DIRECT_DP_PULLUP_HISEL_MASK USBCTRL_USBPHY_DIRECT_DP_PULLUP_HISEL(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DIFFMODE_OVERRIDE_EN(v) (((v)&0x1)<<15)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DIFFMODE_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DIFFMODE_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_OVERRIDE_EN(v) (((v)&0x1)<<12)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_FSSLEW_OVERRIDE_EN(v) (((v)&0x1)<<11)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_FSSLEW_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_FSSLEW_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_PD_OVERRIDE_EN(v) (((v)&0x1)<<10)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_PD_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_PD_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_RX_PD_OVERRIDE_EN(v) (((v)&0x1)<<9)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_RX_PD_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_RX_PD_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OVERRIDE_EN(v) (((v)&0x1)<<8)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OVERRIDE_EN(v) (((v)&0x1)<<7)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OE_OVERRIDE_EN(v) (((v)&0x1)<<6)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OE_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OE_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OE_OVERRIDE_EN(v) (((v)&0x1)<<5)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OE_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OE_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLDN_EN_OVERRIDE_EN(v) (((v)&0x1)<<4)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLDN_EN_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLDN_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLDN_EN_OVERRIDE_EN(v) (((v)&0x1)<<3)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLDN_EN_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLDN_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_EN_OVERRIDE_EN(v) (((v)&0x1)<<2)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_EN_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_HISEL_OVERRIDE_EN(v) (((v)&0x1)<<1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_HISEL_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_HISEL_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_HISEL_OVERRIDE_EN(v) (((v)&0x1)<<0)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_HISEL_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_HISEL_OVERRIDE_EN(ALL1)

/*USBPHY_DIRECT_OVERRIDE Register macros*/

#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DIFFMODE_OVERRIDE_EN(v) (((v)&0x1)<<15)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DIFFMODE_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DIFFMODE_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_OVERRIDE_EN(v) (((v)&0x1)<<12)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_FSSLEW_OVERRIDE_EN(v) (((v)&0x1)<<11)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_FSSLEW_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_FSSLEW_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_PD_OVERRIDE_EN(v) (((v)&0x1)<<10)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_PD_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_PD_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_RX_PD_OVERRIDE_EN(v) (((v)&0x1)<<9)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_RX_PD_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_RX_PD_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OVERRIDE_EN(v) (((v)&0x1)<<8)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OVERRIDE_EN(v) (((v)&0x1)<<7)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OE_OVERRIDE_EN(v) (((v)&0x1)<<6)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OE_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DM_OE_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OE_OVERRIDE_EN(v) (((v)&0x1)<<5)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OE_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_TX_DP_OE_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLDN_EN_OVERRIDE_EN(v) (((v)&0x1)<<4)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLDN_EN_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLDN_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLDN_EN_OVERRIDE_EN(v) (((v)&0x1)<<3)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLDN_EN_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLDN_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_EN_OVERRIDE_EN(v) (((v)&0x1)<<2)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_EN_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_EN_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_HISEL_OVERRIDE_EN(v) (((v)&0x1)<<1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_HISEL_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DM_PULLUP_HISEL_OVERRIDE_EN(ALL1)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_HISEL_OVERRIDE_EN(v) (((v)&0x1)<<0)
#define USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_HISEL_OVERRIDE_EN_MASK USBCTRL_USBPHY_DIRECT_OVERRIDE_DP_PULLUP_HISEL_OVERRIDE_EN(ALL1)

/*USBPHY_TRIM Register macros*/

#define USBCTRL_USBPHY_TRIM_DM_PULLDN_TRIM(v) (((v)&0x1f)<<8)
#define USBCTRL_USBPHY_TRIM_DM_PULLDN_TRIM_MASK USBCTRL_USBPHY_TRIM_DM_PULLDN_TRIM(ALL1)
#define USBCTRL_USBPHY_TRIM_DP_PULLDN_TRIM(v) (((v)&0x1f)<<0)
#define USBCTRL_USBPHY_TRIM_DP_PULLDN_TRIM_MASK USBCTRL_USBPHY_TRIM_DP_PULLDN_TRIM(ALL1)

/*INTR Register macros*/

#define USBCTRL_INTR_EP_STALL_NAK(v) (((v)&0x1)<<19)
#define USBCTRL_INTR_EP_STALL_NAK_MASK USBCTRL_INTR_EP_STALL_NAK(ALL1)
#define USBCTRL_INTR_ABORT_DONE(v) (((v)&0x1)<<18)
#define USBCTRL_INTR_ABORT_DONE_MASK USBCTRL_INTR_ABORT_DONE(ALL1)
#define USBCTRL_INTR_DEV_SOF(v) (((v)&0x1)<<17)
#define USBCTRL_INTR_DEV_SOF_MASK USBCTRL_INTR_DEV_SOF(ALL1)
#define USBCTRL_INTR_SETUP_REQ(v) (((v)&0x1)<<16)
#define USBCTRL_INTR_SETUP_REQ_MASK USBCTRL_INTR_SETUP_REQ(ALL1)
#define USBCTRL_INTR_DEV_RESUME_FROM_HOST(v) (((v)&0x1)<<15)
#define USBCTRL_INTR_DEV_RESUME_FROM_HOST_MASK USBCTRL_INTR_DEV_RESUME_FROM_HOST(ALL1)
#define USBCTRL_INTR_DEV_SUSPEND(v) (((v)&0x1)<<14)
#define USBCTRL_INTR_DEV_SUSPEND_MASK USBCTRL_INTR_DEV_SUSPEND(ALL1)
#define USBCTRL_INTR_DEV_CONN_DIS(v) (((v)&0x1)<<13)
#define USBCTRL_INTR_DEV_CONN_DIS_MASK USBCTRL_INTR_DEV_CONN_DIS(ALL1)
#define USBCTRL_INTR_BUS_RESET(v) (((v)&0x1)<<12)
#define USBCTRL_INTR_BUS_RESET_MASK USBCTRL_INTR_BUS_RESET(ALL1)
#define USBCTRL_INTR_VBUS_DETECT(v) (((v)&0x1)<<11)
#define USBCTRL_INTR_VBUS_DETECT_MASK USBCTRL_INTR_VBUS_DETECT(ALL1)
#define USBCTRL_INTR_STALL(v) (((v)&0x1)<<10)
#define USBCTRL_INTR_STALL_MASK USBCTRL_INTR_STALL(ALL1)
#define USBCTRL_INTR_ERROR_CRC(v) (((v)&0x1)<<9)
#define USBCTRL_INTR_ERROR_CRC_MASK USBCTRL_INTR_ERROR_CRC(ALL1)
#define USBCTRL_INTR_ERROR_BIT_STUFF(v) (((v)&0x1)<<8)
#define USBCTRL_INTR_ERROR_BIT_STUFF_MASK USBCTRL_INTR_ERROR_BIT_STUFF(ALL1)
#define USBCTRL_INTR_ERROR_RX_OVERFLOW(v) (((v)&0x1)<<7)
#define USBCTRL_INTR_ERROR_RX_OVERFLOW_MASK USBCTRL_INTR_ERROR_RX_OVERFLOW(ALL1)
#define USBCTRL_INTR_ERROR_RX_TIMEOUT(v) (((v)&0x1)<<6)
#define USBCTRL_INTR_ERROR_RX_TIMEOUT_MASK USBCTRL_INTR_ERROR_RX_TIMEOUT(ALL1)
#define USBCTRL_INTR_ERROR_DATA_SEQ(v) (((v)&0x1)<<5)
#define USBCTRL_INTR_ERROR_DATA_SEQ_MASK USBCTRL_INTR_ERROR_DATA_SEQ(ALL1)
#define USBCTRL_INTR_BUFF_STATUS(v) (((v)&0x1)<<4)
#define USBCTRL_INTR_BUFF_STATUS_MASK USBCTRL_INTR_BUFF_STATUS(ALL1)
#define USBCTRL_INTR_TRANS_COMPLETE(v) (((v)&0x1)<<3)
#define USBCTRL_INTR_TRANS_COMPLETE_MASK USBCTRL_INTR_TRANS_COMPLETE(ALL1)
#define USBCTRL_INTR_HOST_SOF(v) (((v)&0x1)<<2)
#define USBCTRL_INTR_HOST_SOF_MASK USBCTRL_INTR_HOST_SOF(ALL1)
#define USBCTRL_INTR_HOST_RESUME(v) (((v)&0x1)<<1)
#define USBCTRL_INTR_HOST_RESUME_MASK USBCTRL_INTR_HOST_RESUME(ALL1)
#define USBCTRL_INTR_HOST_CONN_DIS(v) (((v)&0x1)<<0)
#define USBCTRL_INTR_HOST_CONN_DIS_MASK USBCTRL_INTR_HOST_CONN_DIS(ALL1)

/*INTE Register macros*/

#define USBCTRL_INTE_EP_STALL_NAK(v) (((v)&0x1)<<19)
#define USBCTRL_INTE_EP_STALL_NAK_MASK USBCTRL_INTE_EP_STALL_NAK(ALL1)
#define USBCTRL_INTE_ABORT_DONE(v) (((v)&0x1)<<18)
#define USBCTRL_INTE_ABORT_DONE_MASK USBCTRL_INTE_ABORT_DONE(ALL1)
#define USBCTRL_INTE_DEV_SOF(v) (((v)&0x1)<<17)
#define USBCTRL_INTE_DEV_SOF_MASK USBCTRL_INTE_DEV_SOF(ALL1)
#define USBCTRL_INTE_SETUP_REQ(v) (((v)&0x1)<<16)
#define USBCTRL_INTE_SETUP_REQ_MASK USBCTRL_INTE_SETUP_REQ(ALL1)
#define USBCTRL_INTE_DEV_RESUME_FROM_HOST(v) (((v)&0x1)<<15)
#define USBCTRL_INTE_DEV_RESUME_FROM_HOST_MASK USBCTRL_INTE_DEV_RESUME_FROM_HOST(ALL1)
#define USBCTRL_INTE_DEV_SUSPEND(v) (((v)&0x1)<<14)
#define USBCTRL_INTE_DEV_SUSPEND_MASK USBCTRL_INTE_DEV_SUSPEND(ALL1)
#define USBCTRL_INTE_DEV_CONN_DIS(v) (((v)&0x1)<<13)
#define USBCTRL_INTE_DEV_CONN_DIS_MASK USBCTRL_INTE_DEV_CONN_DIS(ALL1)
#define USBCTRL_INTE_BUS_RESET(v) (((v)&0x1)<<12)
#define USBCTRL_INTE_BUS_RESET_MASK USBCTRL_INTE_BUS_RESET(ALL1)
#define USBCTRL_INTE_VBUS_DETECT(v) (((v)&0x1)<<11)
#define USBCTRL_INTE_VBUS_DETECT_MASK USBCTRL_INTE_VBUS_DETECT(ALL1)
#define USBCTRL_INTE_STALL(v) (((v)&0x1)<<10)
#define USBCTRL_INTE_STALL_MASK USBCTRL_INTE_STALL(ALL1)
#define USBCTRL_INTE_ERROR_CRC(v) (((v)&0x1)<<9)
#define USBCTRL_INTE_ERROR_CRC_MASK USBCTRL_INTE_ERROR_CRC(ALL1)
#define USBCTRL_INTE_ERROR_BIT_STUFF(v) (((v)&0x1)<<8)
#define USBCTRL_INTE_ERROR_BIT_STUFF_MASK USBCTRL_INTE_ERROR_BIT_STUFF(ALL1)
#define USBCTRL_INTE_ERROR_RX_OVERFLOW(v) (((v)&0x1)<<7)
#define USBCTRL_INTE_ERROR_RX_OVERFLOW_MASK USBCTRL_INTE_ERROR_RX_OVERFLOW(ALL1)
#define USBCTRL_INTE_ERROR_RX_TIMEOUT(v) (((v)&0x1)<<6)
#define USBCTRL_INTE_ERROR_RX_TIMEOUT_MASK USBCTRL_INTE_ERROR_RX_TIMEOUT(ALL1)
#define USBCTRL_INTE_ERROR_DATA_SEQ(v) (((v)&0x1)<<5)
#define USBCTRL_INTE_ERROR_DATA_SEQ_MASK USBCTRL_INTE_ERROR_DATA_SEQ(ALL1)
#define USBCTRL_INTE_BUFF_STATUS(v) (((v)&0x1)<<4)
#define USBCTRL_INTE_BUFF_STATUS_MASK USBCTRL_INTE_BUFF_STATUS(ALL1)
#define USBCTRL_INTE_TRANS_COMPLETE(v) (((v)&0x1)<<3)
#define USBCTRL_INTE_TRANS_COMPLETE_MASK USBCTRL_INTE_TRANS_COMPLETE(ALL1)
#define USBCTRL_INTE_HOST_SOF(v) (((v)&0x1)<<2)
#define USBCTRL_INTE_HOST_SOF_MASK USBCTRL_INTE_HOST_SOF(ALL1)
#define USBCTRL_INTE_HOST_RESUME(v) (((v)&0x1)<<1)
#define USBCTRL_INTE_HOST_RESUME_MASK USBCTRL_INTE_HOST_RESUME(ALL1)
#define USBCTRL_INTE_HOST_CONN_DIS(v) (((v)&0x1)<<0)
#define USBCTRL_INTE_HOST_CONN_DIS_MASK USBCTRL_INTE_HOST_CONN_DIS(ALL1)

/*INTF Register macros*/

#define USBCTRL_INTF_EP_STALL_NAK(v) (((v)&0x1)<<19)
#define USBCTRL_INTF_EP_STALL_NAK_MASK USBCTRL_INTF_EP_STALL_NAK(ALL1)
#define USBCTRL_INTF_ABORT_DONE(v) (((v)&0x1)<<18)
#define USBCTRL_INTF_ABORT_DONE_MASK USBCTRL_INTF_ABORT_DONE(ALL1)
#define USBCTRL_INTF_DEV_SOF(v) (((v)&0x1)<<17)
#define USBCTRL_INTF_DEV_SOF_MASK USBCTRL_INTF_DEV_SOF(ALL1)
#define USBCTRL_INTF_SETUP_REQ(v) (((v)&0x1)<<16)
#define USBCTRL_INTF_SETUP_REQ_MASK USBCTRL_INTF_SETUP_REQ(ALL1)
#define USBCTRL_INTF_DEV_RESUME_FROM_HOST(v) (((v)&0x1)<<15)
#define USBCTRL_INTF_DEV_RESUME_FROM_HOST_MASK USBCTRL_INTF_DEV_RESUME_FROM_HOST(ALL1)
#define USBCTRL_INTF_DEV_SUSPEND(v) (((v)&0x1)<<14)
#define USBCTRL_INTF_DEV_SUSPEND_MASK USBCTRL_INTF_DEV_SUSPEND(ALL1)
#define USBCTRL_INTF_DEV_CONN_DIS(v) (((v)&0x1)<<13)
#define USBCTRL_INTF_DEV_CONN_DIS_MASK USBCTRL_INTF_DEV_CONN_DIS(ALL1)
#define USBCTRL_INTF_BUS_RESET(v) (((v)&0x1)<<12)
#define USBCTRL_INTF_BUS_RESET_MASK USBCTRL_INTF_BUS_RESET(ALL1)
#define USBCTRL_INTF_VBUS_DETECT(v) (((v)&0x1)<<11)
#define USBCTRL_INTF_VBUS_DETECT_MASK USBCTRL_INTF_VBUS_DETECT(ALL1)
#define USBCTRL_INTF_STALL(v) (((v)&0x1)<<10)
#define USBCTRL_INTF_STALL_MASK USBCTRL_INTF_STALL(ALL1)
#define USBCTRL_INTF_ERROR_CRC(v) (((v)&0x1)<<9)
#define USBCTRL_INTF_ERROR_CRC_MASK USBCTRL_INTF_ERROR_CRC(ALL1)
#define USBCTRL_INTF_ERROR_BIT_STUFF(v) (((v)&0x1)<<8)
#define USBCTRL_INTF_ERROR_BIT_STUFF_MASK USBCTRL_INTF_ERROR_BIT_STUFF(ALL1)
#define USBCTRL_INTF_ERROR_RX_OVERFLOW(v) (((v)&0x1)<<7)
#define USBCTRL_INTF_ERROR_RX_OVERFLOW_MASK USBCTRL_INTF_ERROR_RX_OVERFLOW(ALL1)
#define USBCTRL_INTF_ERROR_RX_TIMEOUT(v) (((v)&0x1)<<6)
#define USBCTRL_INTF_ERROR_RX_TIMEOUT_MASK USBCTRL_INTF_ERROR_RX_TIMEOUT(ALL1)
#define USBCTRL_INTF_ERROR_DATA_SEQ(v) (((v)&0x1)<<5)
#define USBCTRL_INTF_ERROR_DATA_SEQ_MASK USBCTRL_INTF_ERROR_DATA_SEQ(ALL1)
#define USBCTRL_INTF_BUFF_STATUS(v) (((v)&0x1)<<4)
#define USBCTRL_INTF_BUFF_STATUS_MASK USBCTRL_INTF_BUFF_STATUS(ALL1)
#define USBCTRL_INTF_TRANS_COMPLETE(v) (((v)&0x1)<<3)
#define USBCTRL_INTF_TRANS_COMPLETE_MASK USBCTRL_INTF_TRANS_COMPLETE(ALL1)
#define USBCTRL_INTF_HOST_SOF(v) (((v)&0x1)<<2)
#define USBCTRL_INTF_HOST_SOF_MASK USBCTRL_INTF_HOST_SOF(ALL1)
#define USBCTRL_INTF_HOST_RESUME(v) (((v)&0x1)<<1)
#define USBCTRL_INTF_HOST_RESUME_MASK USBCTRL_INTF_HOST_RESUME(ALL1)
#define USBCTRL_INTF_HOST_CONN_DIS(v) (((v)&0x1)<<0)
#define USBCTRL_INTF_HOST_CONN_DIS_MASK USBCTRL_INTF_HOST_CONN_DIS(ALL1)

/*INTS Register macros*/

#define USBCTRL_INTS_EP_STALL_NAK(v) (((v)&0x1)<<19)
#define USBCTRL_INTS_EP_STALL_NAK_MASK USBCTRL_INTS_EP_STALL_NAK(ALL1)
#define USBCTRL_INTS_ABORT_DONE(v) (((v)&0x1)<<18)
#define USBCTRL_INTS_ABORT_DONE_MASK USBCTRL_INTS_ABORT_DONE(ALL1)
#define USBCTRL_INTS_DEV_SOF(v) (((v)&0x1)<<17)
#define USBCTRL_INTS_DEV_SOF_MASK USBCTRL_INTS_DEV_SOF(ALL1)
#define USBCTRL_INTS_SETUP_REQ(v) (((v)&0x1)<<16)
#define USBCTRL_INTS_SETUP_REQ_MASK USBCTRL_INTS_SETUP_REQ(ALL1)
#define USBCTRL_INTS_DEV_RESUME_FROM_HOST(v) (((v)&0x1)<<15)
#define USBCTRL_INTS_DEV_RESUME_FROM_HOST_MASK USBCTRL_INTS_DEV_RESUME_FROM_HOST(ALL1)
#define USBCTRL_INTS_DEV_SUSPEND(v) (((v)&0x1)<<14)
#define USBCTRL_INTS_DEV_SUSPEND_MASK USBCTRL_INTS_DEV_SUSPEND(ALL1)
#define USBCTRL_INTS_DEV_CONN_DIS(v) (((v)&0x1)<<13)
#define USBCTRL_INTS_DEV_CONN_DIS_MASK USBCTRL_INTS_DEV_CONN_DIS(ALL1)
#define USBCTRL_INTS_BUS_RESET(v) (((v)&0x1)<<12)
#define USBCTRL_INTS_BUS_RESET_MASK USBCTRL_INTS_BUS_RESET(ALL1)
#define USBCTRL_INTS_VBUS_DETECT(v) (((v)&0x1)<<11)
#define USBCTRL_INTS_VBUS_DETECT_MASK USBCTRL_INTS_VBUS_DETECT(ALL1)
#define USBCTRL_INTS_STALL(v) (((v)&0x1)<<10)
#define USBCTRL_INTS_STALL_MASK USBCTRL_INTS_STALL(ALL1)
#define USBCTRL_INTS_ERROR_CRC(v) (((v)&0x1)<<9)
#define USBCTRL_INTS_ERROR_CRC_MASK USBCTRL_INTS_ERROR_CRC(ALL1)
#define USBCTRL_INTS_ERROR_BIT_STUFF(v) (((v)&0x1)<<8)
#define USBCTRL_INTS_ERROR_BIT_STUFF_MASK USBCTRL_INTS_ERROR_BIT_STUFF(ALL1)
#define USBCTRL_INTS_ERROR_RX_OVERFLOW(v) (((v)&0x1)<<7)
#define USBCTRL_INTS_ERROR_RX_OVERFLOW_MASK USBCTRL_INTS_ERROR_RX_OVERFLOW(ALL1)
#define USBCTRL_INTS_ERROR_RX_TIMEOUT(v) (((v)&0x1)<<6)
#define USBCTRL_INTS_ERROR_RX_TIMEOUT_MASK USBCTRL_INTS_ERROR_RX_TIMEOUT(ALL1)
#define USBCTRL_INTS_ERROR_DATA_SEQ(v) (((v)&0x1)<<5)
#define USBCTRL_INTS_ERROR_DATA_SEQ_MASK USBCTRL_INTS_ERROR_DATA_SEQ(ALL1)
#define USBCTRL_INTS_BUFF_STATUS(v) (((v)&0x1)<<4)
#define USBCTRL_INTS_BUFF_STATUS_MASK USBCTRL_INTS_BUFF_STATUS(ALL1)
#define USBCTRL_INTS_TRANS_COMPLETE(v) (((v)&0x1)<<3)
#define USBCTRL_INTS_TRANS_COMPLETE_MASK USBCTRL_INTS_TRANS_COMPLETE(ALL1)
#define USBCTRL_INTS_HOST_SOF(v) (((v)&0x1)<<2)
#define USBCTRL_INTS_HOST_SOF_MASK USBCTRL_INTS_HOST_SOF(ALL1)
#define USBCTRL_INTS_HOST_RESUME(v) (((v)&0x1)<<1)
#define USBCTRL_INTS_HOST_RESUME_MASK USBCTRL_INTS_HOST_RESUME(ALL1)
#define USBCTRL_INTS_HOST_CONN_DIS(v) (((v)&0x1)<<0)
#define USBCTRL_INTS_HOST_CONN_DIS_MASK USBCTRL_INTS_HOST_CONN_DIS(ALL1)

#endif