#ifndef _IRQ_H
_IRQ_H

enum _IRQ_NUMS { 
	TIMER0_IRQ, TIMER1_IRQ, TIMER2_IRQ, TIMER3_IRQ, PWM_IRQ, 
	USBCTRL_IRQ, XIP_IRQ, PIO0_IRQ0, PIO0_IRQ1, PIO1_IRQ0,
	PIO1_IRQ1, DMA_IRQ0, DMA_IRQ1, IO_BANK0_IRQ, IO_QSPI_IRQ,
	SIO_IRQ0, SIO_IRQ1, CLOCKS_IRQ, SPI0_IRQ, SPI1_IRQ, UART0_IRQ,
	UART1_IRQ, ADC_IRQ, I2C0_IRQ, I2C1_IRQ, RTC_IRQ
	};

#endif

